### ISSUE TITLE
Blahaj.transgirl.dev is offline

### ISSUE THREAD

**Issue by DutchSlav** [CatgirlApril/BlahajAPI#3]
View the title.
Error is 502 bad gateway on Cloudflare.
Ray ID: 85a9e4f5195f66cf

**Comment by CatgirlApril** [comment]
Won't go into the why, but the site will be down for a few days whilst I fix some things, sorry for the inconvenience, I'll update this issue when it's back

**Comment by CatgirlApril** [comment]
Okay the API is now back online, however it may be unstable over the next few days
